cards = [
  //Нейтральные
  {
    id: 1,
    name: "⚔️ Геральт из Ривии",
    hero: "hero",
    power: 15,
    row: "melee",
    skill: "plotva",
    fraction: "neutral",
  },
  {
    id: 2,
    name: "⚔️ Авалак'х",
    hero: "hero",
    power: 0,
    row: "melee",
    skill: "spy",
    fraction: "neutral",
  },
  {
    id: 3,
    name: "⚔️ Лютик",
    hero: "",
    power: 2,
    row: "melee",
    skill: "horn",
    fraction: "neutral",
  },
  {
    id: 4,
    name: "⚔️ Золтан Хивай",
    hero: "",
    power: 5,
    row: "melee",
    skill: "",
    fraction: "neutral",
  },
  {
    id: 5,
    name: "⚔️ Эмиель Регис",
    hero: "",
    power: 5,
    row: "melee",
    skill: "",
    fraction: "neutral",
  },
  {
    id: 6,
    name: "⚔️ Весемир",
    hero: "",
    power: 6,
    row: "melee",
    skill: "",
    fraction: "neutral",
  },
  {
    id: 7,
    name: "⚔️ Виллентретенмерт",
    hero: "",
    power: 7,
    row: "melee",
    skill: "execution",
    fraction: "neutral",
  },
  {
    id: 8,
    name: "🏹 Йеннифер",
    hero: "hero",
    power: 7,
    row: "range",
    skill: "medic",
    fraction: "neutral",
  },
  {
    id: 9,
    name: "⚔️ Трисс Меригольд",
    hero: "hero",
    power: 7,
    row: "melee",
    skill: "",
    fraction: "neutral",
  },
  {
    id: 10,
    name: "⚔️ Цирилла",
    hero: "hero",
    power: 15,
    row: "melee",
    skill: "plotva",
    fraction: "neutral",
  },
  {
    id: 11,
    name: "⚔️ Ольгерд фон Эверек",
    hero: "",
    power: 6,
    row: "melee",
    skill: "morale",
    fraction: "neutral",
  },
  {
    id: 12,
    name: "🏹 Ольгерд фон Эверек",
    hero: "",
    power: 6,
    row: "range",
    skill: "morale",
    fraction: "neutral",
  },
  {
    id: 13,
    name: "🏰 Гюнтер о'Дим",
    hero: "",
    power: 2,
    row: "siege",
    skill: "double",
    fraction: "neutral",
  },
  {
    id: 14,
    name: "🏹 Гюнтер о'Дим: Тьма",
    hero: "",
    power: 4,
    row: "range",
    skill: "double",
    fraction: "neutral",
  },
  {
    id: 15,
    name: "⚔️ Плотва",
    hero: "",
    power: 3,
    row: "melee",
    skill: "",
    fraction: "neutral",
  },

  //Северные королевства
  //Герои
  {
    name: "Вернон Роше",
    hero: "hero",
    power: 10,
    row: "melee",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Ян Наталис",
    hero: "hero",
    power: 10,
    row: "melee",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Эстерад Тиссен",
    hero: "hero",
    power: 10,
    row: "melee",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Филиппа Эльхарт",
    hero: "hero",
    power: 10,
    row: "range",
    skill: "",
    fraction: "nothern",
  },

  //Обычные
  //Ближний бой

  {
    name: "Реданский пехотинец",
    hero: "",
    power: 1,
    row: "melee",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Грёбаная пехтура",
    hero: "",
    power: 1,
    row: "melee",
    skill: "bond",
    fraction: "nothern",
  },
  {
    name: "Ярпен Зигрин",
    hero: "",
    power: 2,
    row: "melee",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Боец Синих Полосок",
    hero: "",
    power: 4,
    row: "melee",
    skill: "bond",
    fraction: "nothern",
  },
  {
    name: "Сигизмунд Дийкстра",
    hero: "",
    power: 4,
    row: "melee",
    skill: "spy",
    fraction: "nothern",
  },
  {
    name: "Принц Стеннис",
    hero: "",
    power: 5,
    row: "melee",
    skill: "spy",
    fraction: "nothern",
  },
  {
    name: "Зигфрид из Денесле",
    hero: "",
    power: 5,
    row: "melee",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Бьянка",
    hero: "",
    power: 5,
    row: "melee",
    skill: "",
    fraction: "nothern",
  },

  //Дальний бой
  {
    name: "Шелдон Скаггс",
    hero: "",
    power: 4,
    row: "range",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Сабрина Глевиссиг",
    hero: "",
    power: 4,
    row: "range",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Рубайлы из Кринфрида",
    hero: "",
    power: 5,
    row: "range",
    skill: "bond",
    fraction: "nothern",
  },
  {
    name: "Шеала де Тансервилль",
    hero: "",
    power: 5,
    row: "range",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Кейра Мец",
    hero: "",
    power: 5,
    row: "range",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Детмольд",
    hero: "",
    power: 6,
    row: "range",
    skill: "",
    fraction: "nothern",
  },

  //Осадные

  {
    name: "Каэдвенский осадный мастер",
    hero: "",
    power: 1,
    row: "siege",
    skill: "morale",
    fraction: "nothern",
  },
  {
    name: "Талер",
    hero: "",
    power: 1,
    row: "siege",
    skill: "spy",
    fraction: "nothern",
  },
  {
    name: "Лекарь Бурой Хоругви",
    hero: "",
    power: 5,
    row: "siege",
    skill: "medic",
    fraction: "nothern",
  },
  {
    name: "Осадная башня",
    hero: "",
    power: 6,
    row: "siege",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Баллиста",
    hero: "",
    power: 6,
    row: "siege",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Требушет",
    hero: "",
    power: 6,
    row: "siege",
    skill: "",
    fraction: "nothern",
  },
  {
    name: "Катапульта",
    hero: "",
    power: 8,
    row: "siege",
    skill: "bond",
    fraction: "nothern",
  },
];
